# -*- coding: utf-8 -*-
{
    'name': "Sistema de Administración de Taller",
    'version': '1.0',
    'summary': "Administra las operaciones de un taller de fotocopiadoras",
    'sequence': -100,
    'description': """Gestiona reparaciones, mantenimientos y más.""",
    'author': "Isidro vera polo",
    'website': "https://copiercompanysac.com",
    'category': 'Services',
    'depends': ['base','mail','contacts','sale_management','portal','web'],
    'data': [
        #'security/ir.model.access.csv',  # Descomenta si tienes este archivo
        'views/ventas.xml',
        'views/templates.xml',
        'data/ir_secuense.xml',
        'data/ir_secuense_ticket.xml',
        'views/modelos.xml',
        'views/repuestos_alquiler.xml',
        'views/marcas.xml',
        'views/informes.xml',
        'views/fallas.xml',
        'data/ir.secuense_info.xml',
        'data/ir_secuense_ev.xml',
        'data/print.xml',
        'reports/reparaciones_repor.xml',
        'reports/ticket_reporte.xml',
        'reports/informes.xml',
        'reports/evaluacion.xml',
        'reports/report_qr_codes_reparaciones.xml',
        'reports/qr_alquiler.xml',
        'data/cron_data.xml',
        'data/cron_evaluador_diario.xml',
        'views/reporte_cotizacion.xml',
        'views/reparaciones.xml',        
        'views/opciones_cliente.xml',
        'security/acceso.xml',
        'security/ir.model.access.csv',
        'views/alquiler.xml',
        'views/opciones_product.xml',        
        'views/sale_order_.xml',
        'views/linea_pedido.xml',
        'views/mail_maquinas.xml',
        'views/evaluacion.xml',
        'views/crear_ticket_portal.xml',
        'views/incidencias.xml',
        'views/soporte.alquiler.xml',
        #'wizard/wizard.xml',        
        'data/ir.secuence_incidencia.xml',
        'views/template_formulario_ticket.xml',               
        'data/plantillas_correo.xml',
        'views/pagina_con_opciones.xml',
        'views/reportar_incidencia_form.xml',
        'views/solicitar_toner_form.xml',
        'views/pagina_confirmacion.xml',
        'views/solicitar_toner_form_template.xml',
        'views/pagina_confirmacion_toner.xml',
        'views/repuestos_alquiler_list.xml',
        'views/soporte_dashboard.xml',
        'views/transportistas.xml',
        
        
    ],
    'demo': [
        'demo/demo_data.xml',
    ],
    'assets': {
    'web.assets_backend': [
        'sat/static/src/js/tree_button.js',
        'sat/static/src/js/evaluacion.js',        
        'sat/static/src/css/evaluacion.css',        
    ],
    'web.assets_qweb': [
        'sat/static/src/xml/tree_button.xml',        
    ],
    },
    'qweb': [
        'static/src/xml/*.xml',
    ],
    'js': [
        'static/src/js/*.js',
    ],
   

    'installable': True,
    'application': True,
    'auto_install': False,
}
