# -*- coding: utf-8 -*-
from . import ticket_informe_mixin
from . import models
from . import marcas
from . import tipo_maquina
from . import modelos
from . import opciones_product
from . import soporte_alquiler
from . import lineas_pedido
from . import sale_order_
from . import evaluacion
from . import ajustes
from . import alquiler
from . import informes
from . import opciones_cliente
from . import registro_fallas
from . import reparaciones
from . import repuestos_alquiler
from . import incidencias
from . import importacionexcel
from . import sat_dashboard
from . import reparacion_autenticacion_wizard
from . import fotos_reparaciones
from . import ticket_create_import
from . import onboarding
from . import technical_service_evaluation
from . import tickets_mensuales
from . import whatsapp_notification_wizard
from . import toner_delivery_confirmation
from . import toner_delivery
from . import toner_solicitudes
from . import inspeccion_equipo
from . import solicitud_partes
from . import solicitud_partes_linea
from . import wizard_inspeccion
from . import contador_automatico
from . import patron_contador
from . import contador_dashboard
from . import print_tracker
from . import mail_message_inherit
from . import alquiler_maintenance
from . import alquiler_consumables
from . import alquiler_blocking
from . import printtracker_entity
from . import printtracker_entity_address
from . import printtracker_entity_label
from . import printtracker_meter
from . import printtracker_supply
from . import printtracker_alert
from . import printtracker_alert_manager
from . import printtracker_consolidator
from . import printtracker_daily_reading
from . import reporte_maquinas_alquiler
from . import reporte_estado_maquinas
from . import modelo_maquina_componentes
from . import checklist_map
from . import informe_regla
from . import componente
from . import reparacion_intervencion
from . import reparacion_subpartes_wizard
from . import componente_estado
from . import accesorio_tipo
from . import modelo_maquina_accesorio
from . import accesorio_estado
from . import color_tipo
from . import componente_color
from . import reparacion_componente_evaluacion
from . import reparaciones_migration
from . import soporte_mensajes
from . import contadores_ticket
from . import reparaciones_mensajes
from . import reparaciones_informe
from . import accesorio_subparte
from . import reparacion_accesorio_evaluacion
from . import wizard_asignar_componentes
from . import gemini_config
from . import modelo_maquina
from . import sat_import_line