'data/ir_secuense.xml',
        
        
               
        'report/qr_alquiler.xml',                
        'report/evaluacion_servicio.xml',









        'data/plantillas_correo.xml',
        'data/correos_reparaciones.xml',
        'data/correos_tickets.xml',
        'data/correos_informes.xml',
        'data/correos_maquinas.xml',
        'data/correos_alquiler.xml',
        'data/mail_permisos.xml',
        'data/correos_evaluaciones_tecnicos.xml',
        'data/email_templates_consolidated.xml',
        'data/componente_color_data.xml', 
        'data/color_tipo_data.xml',
        'data/accesorio_tipo_data.xml',
        'data/componente_tipo_data.xml',
        'data/componente_subparte_data.xml',
        'data/componente_estado_data.xml',
        'data/accesorio_estado_data.xml',
        'data/ir_actions_server_migration.xml',        
        'views/ventas.xml',   
        'views/modelos.xml',
        'views/repuestos_alquiler.xml',
        'views/marcas.xml',
        'views/informes.xml',
        'views/fallas.xml',
        'views/reporte_cotizacion.xml',
        'views/reparaciones.xml',
        'views/opciones_cliente.xml',
        'views/alquiler.xml',
        'views/opciones_product.xml',
        'views/sale_order_.xml',
        'views/linea_pedido.xml',
        'views/mail_maquinas.xml',
        'views/evaluacion.xml',
        'views/crear_ticket_portal.xml',
        'views/incidencias.xml',
        'views/soporte.alquiler.xml',
        'views/template_formulario_ticket.xml',
        'views/pagina_con_opciones.xml',
        'views/reportar_incidencia_form.xml',
        'views/pagina_confirmacion.xml',
        'views/solicitar_toner_form_template.xml',
        'views/pagina_confirmacion_toner.xml',
        'views/repuestos_alquiler_list.xml',
        'views/soporte_dashboard.xml',
        'views/transportistas.xml',
        'views/graficos.xml',
        'views/customer_records_page.xml',
        'views/importacionexcel.xml',
        'views/reparacion_autenticacion_wizard_view.xml',
        'views/fotos_reparaciones.xml',
        'views/gallery_templates.xml',
        'views/ticket_create_import_views.xml',
        'views/banner_prueba.xml',
        'views/templates_mantenimientos.xml',
        'views/alquiler_views.xml',
        'views/evaluacion_tecnicos_alquiler.xml',
        'views/template_evaluacion_tecnicos.xml',
        'views/levantamiento.xml',
        'views/inspeccion_vista.xml',
        'views/solicitud_partes.xml',
        'views/solicitud_template.xml',
        'views/solicitud_partes_views.xml',
        'views/partes_templates_alquiler.xml',
        'views/envio_masivo_evaluaciones.xml',
        'views/equipment_visit_report_views.xml',
        'views/leave_request_template.xml',
        'report/equipment_visit_report.xml',
        'views/whatsapp_notification_wizard_views.xml',
        'views/view_toner_counter_submission.xml',
        'views/view_toner_delivery_confirmation.xml',
        'views/view_toner_delivery_schedule.xml',
        'views/view_contador_automatico.xml',
        'views/view_patron_contador.xml',        
        'views/printtracker_views.xml',
        'views/reporte_maquinas_alquiler.xml',
        'views/tickets_masivos.xml',
        'views/componente.tipo.xml',
        'views/componente.subparte.xml',
        'views/modelo.maquina.componente.xml',
        'views/informe.regla.xml',
        'views/checklist.componente.map.xml',
        'views/reparacion_intervencion_views.xml',
        'views/componente_estado_views.xml',
        'views/accesorio_catalogos_views.xml',
        'views/reparacion_componente_evaluacion_views.xml',
        'views/solicitud_partes_wizards_views.xml',
        'views/partes_templates_publicos.xml',
        'views/reparacion_accesorio_evaluacion_views.xml',
        'views/wizard_asignar_componentes_views.xml',
        'views/gemini_config_views.xml',
        'views/modelo_accesorios.xml',
        'views/sat_import_line_views.xml',
        'views/portal_templates.xml',
        'views/traccar_tracking_views.xml',
        'views/mdm_views.xml',
        'views/tracking_diagnostico_views.xml',      
        'wizards/sat_import_assign_header_wizard_views.xml',
        'wizards/sat_entrega_wizard_view.xml',
        'views/solicitud_parte_tecnico_views.xml',
        'views/solicitud_partes_portal.xml',